urls.py
from __future__ import unicode_literals

from django.conf.urls import patterns, include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin

from mezzanine.core.views import direct_to_template


admin.autodiscover()

# Add the urlpatterns for any custom Django applications here.
# You can also change the ``home`` view to add your own functionality
# to the project's homepage.

urlpatterns = i18n_patterns("",
    # Change the admin prefix here to use an alternate URL for the
    # admin interface, which would be marginally more secure.
    ("^admin/", include(admin.site.urls)),
)

urlpatterns += patterns('',

    # We don't want to presume how your homepage works, so here are a
    # few patterns you can use to set it up.

    # HOMEPAGE AS STATIC TEMPLATE
    # ---------------------------
    # This pattern simply loads the index.html template. It isn't
    # commented out like the others, so it's the default. You only need
    # one homepage pattern, so if you use a different one, comment this
    # one out.

    url("^$", 'lessons.views.homepage', name="home"),

    # HOMEPAGE AS AN EDITABLE PAGE IN THE PAGE TREE
    # ---------------------------------------------
    # This pattern gives us a normal ``Page`` object, so that your
    # homepage can be managed via the page tree in the admin. If you
    # use this pattern, you'll need to create a page in the page tree,
    # and specify its URL (in the Meta Data section) as "/", which
    # is the value used below in the ``{"slug": "/"}`` part.
    # Also note that the normal rule of adding a custom
    # template per page with the template name using the page's slug
    # doesn't apply here, since we can't have a template called
    # "/.html" - so for this case, the template "pages/index.html"
    # should be used if you want to customize the homepage's template.

    # url("^$", "mezzanine.pages.views.page", {"slug": "/"}, name="home"),

    # HOMEPAGE FOR A BLOG-ONLY SITE
    # -----------------------------
    # This pattern points the homepage to the blog post listing page,
    # and is useful for sites that are primarily blogs. If you use this
    # pattern, you'll also need to set BLOG_SLUG = "" in your
    # ``settings.py`` module, and delete the blog page object from the
    # page tree in the admin if it was installed.

    # url("^$", "mezzanine.blog.views.blog_post_list", name="home"),

    # MEZZANINE'S URLS
    # ----------------
    # ADD YOUR OWN URLPATTERNS *ABOVE* THE LINE BELOW.
    # ``mezzanine.urls`` INCLUDES A *CATCH ALL* PATTERN
    # FOR PAGES, SO URLPATTERNS ADDED BELOW ``mezzanine.urls``
    # WILL NEVER BE MATCHED!

    # If you'd like more granular control over the patterns in
    # ``mezzanine.urls``, go right ahead and take the parts you want
    # from it, and use them directly below instead of using
    # ``mezzanine.urls``.

    # 3rd Party URLs
    (r'^search/', include('haystack.urls')),

    # Local URLS
    url(r'^accounts/', include('accounts.urls')),
    url(r'^lessons/', include('lessons.urls')),
    url('', include('social.apps.django_app.urls', namespace='social')),
    ("^", include("mezzanine.urls")),

    # MOUNTING MEZZANINE UNDER A PREFIX
    # ---------------------------------
    # You can also mount all of Mezzanine's urlpatterns under a
    # URL prefix if desired. When doing this, you need to define the
    # ``SITE_PREFIX`` setting, which will contain the prefix. Eg:
    # SITE_PREFIX = "my/site/prefix"
    # For convenience, and to avoid repeating the prefix, use the
    # commented out pattern below (commenting out the one above of course)
    # which will make use of the ``SITE_PREFIX`` setting. Make sure to
    # add the import ``from django.conf import settings`` to the top
    # of this file as well.
    # Note that for any of the various homepage patterns above, you'll
    # need to use the ``SITE_PREFIX`` setting as well.

    # ("^%s/" % settings.SITE_PREFIX, include("mezzanine.urls"))

)

# Adds ``STATIC_URL`` to the context of error pages, so that error
# pages can use JS, CSS and images.
handler404 = "mezzanine.core.views.page_not_found"
handler500 = "mezzanine.core.views.server_error"

lessons/models.py
import os
import decimal
import requests
import gdata.youtube
import gdata.youtube.service

from datetime import datetime

from django.conf import settings
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.db import models
from django.template.defaultfilters import slugify
from django.utils.translation import ugettext_lazy as _

from embed_video.backends import detect_backend
from embed_video.fields import EmbedVideoField
from mezzanine.generic.fields import CommentsField, KeywordsField
from mezzanine.blog.models import BlogPost
from mptt.models import MPTTModel, TreeForeignKey
from ordered_model.models import OrderedModel


LEVEL_BEGINNER = 1
LEVEL_INTERMEDIATE = 2
LEVEL_ADVANCED = 3
PRODUCT_LEVEL_CHOICES = [
    (LEVEL_BEGINNER, "Beginner"),
    (LEVEL_INTERMEDIATE, "Intermediate"),
    (LEVEL_ADVANCED, "Advanced")
]


def get_image_path(instance, filename):
    """
    Dynamically set upload_to attribute of image fields.
    """
    classname = instance.__class__.__name__.lower()
    return os.path.join('shop', classname, filename)


def get_file_path(instance, filename):
    """
    Dynamically set upload_to attribute of file fields.
    """
    classname = instance.__class__.__name__.lower()
    return os.path.join('files', classname, filename)


class CustomMetaData(models.Model):
    """
    Abstract model that provides meta data for content.
    """
    meta_title = models.CharField(max_length=255, blank=True, null=True)
    meta_description = models.TextField(blank=True, null=True)
    keywords = KeywordsField(verbose_name=_("Keywords"))

    class Meta:
        abstract = True


class HomePage(models.Model):
    ad_top = models.TextField(blank=True, null=True, help_text="Ad script for the top banner")
    ad_bottom_left = models.TextField(blank=True, null=True, help_text="Ad script for the bottom left banner")
    ad_bottom_right = models.TextField(blank=True, null=True, help_text="Ad script for the bottom right banner")

    def __unicode__(self):
        return u"Home Page Settings"


class Category(MPTTModel, CustomMetaData):
    """
    Stores information about Video Categories.
    """
    parent = TreeForeignKey("self", blank=True, null=True, related_name='children')
    title = models.CharField(max_length=64, unique=True)
    slug = models.SlugField(unique=True, blank=True, null=True)
    ad_top = models.TextField(blank=True, null=True, help_text="Ad script for the top banner")

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"

    def __unicode__(self):
        return "%s" % (self.title, )

    def save(self, *args, **kwargs):
        super(Category, self).save(*args, **kwargs)

        if not self.slug:
            self.slug = '%s' % (slugify(self.title), )
            self.save()

    def get_ads(self):
        return self.advertisement_set.all()

    def get_videos(self):
        return self.homepagevideo_set.all()


class Advertisement(models.Model):
    """
    Contains ad script of a particular :model:'lessons.Category' instance.
    """
    category = TreeForeignKey(Category)
    ad_script = models.TextField()

    class Meta:
        verbose_name = "Advertisement"
        verbose_name_plural = "Advertisements"


class BlogAdvertisement(models.Model):
    """
    Contains ad script of a particular :model:'mezzanine.blog.models.BlogPost' instance.
    """
    post = models.ForeignKey(BlogPost)
    ad_script = models.TextField()

    class Meta:
        verbose_name = "Blog Advertisement"
        verbose_name_plural = "Blog Advertisements"


class Product(models.Model):
    """
    Stores information about Product which will then be used in cartridge
    """
    title = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(unique=True, blank=True, null=True)
    category = TreeForeignKey(Category)
    image = models.ImageField(upload_to=get_image_path)
    price = models.DecimalField(decimal_places=2, max_digits=7, default=decimal.Decimal('0.00'))
    admin_percentage = models.DecimalField(decimal_places=2, max_digits=7,
        help_text="Percentage of the Price that goes to Admin", default=decimal.Decimal('0.00'))
    author = models.ForeignKey(User)
    description = models.TextField()
    level = models.PositiveIntegerField(choices=PRODUCT_LEVEL_CHOICES, default=LEVEL_BEGINNER)
    approved = models.BooleanField(default=False)
    approved_date = models.DateTimeField(blank=True, null=True)
    creation_date = models.DateTimeField(default=datetime.now())
    # TODO: Add excess/bonus items

    class Meta:
        verbose_name = "Product"
        verbose_name_plural = "Products"

    def __unicode__(self):
        return "%s" % (self.title, )

    def save(self, *args, **kwargs):
        super(Product, self).save(*args, **kwargs)

        if not self.slug:
            self.slug = slugify(self.title)
            self.save()


class ProductFile(models.Model):
    """
    Stores Files related to Products
    """
    product = models.ForeignKey(Product)
    file_item = models.FileField(upload_to=get_file_path)

    class Meta:
        verbose_name = "Product File"
        verbose_name_plural = "Product Files"

    def __unicode__(self):
        return "%s" % (self.product.title, )


class VideoLesson(OrderedModel, CustomMetaData):
    """
    Stores information about Video Lessons
    """
    user = models.ForeignKey(User)
    category = TreeForeignKey(Category)
    title = models.CharField(max_length=255, blank=True, null=True)
    slug = models.SlugField(max_length=255, unique=True, blank=True, null=True)
    duration = models.PositiveIntegerField("Duration in Seconds", default=0)
    video = EmbedVideoField()
    thumbnail = models.URLField(blank=True, null=True)
    backend_source = models.CharField(max_length=64, blank=True, null=True)
    info = models.TextField(blank=True, null=True)
    related_videos = models.ManyToManyField("self", blank=True, null=True)
    related_products = models.ManyToManyField(Product, blank=True, null=True)
    comments = CommentsField()
    uploaded_date = models.DateTimeField(default=datetime.now())

    order_with_respect_to = 'category'

    class Meta:
        verbose_name = "Video Lesson"
        verbose_name_plural = "Video Lessons"

    # def _get_youtube_info(self, backend):
    #     info = ""
    #     try:
    #         req = requests.get("http://www.youtube.com/oembed?url=http://www.youtube.com/watch?v=%s&format=json" % (backend.code))
    #         info = req.text
    #     except:
    #         pass
    #     return info

    def __unicode__(self):
        return "%s" % (self.title, )

    def _generate_youtube_info(self, entry):
        author = entry.author[0].name.text if entry.author and entry.author[0] else ""
        info = {
            "title": entry.media.title.text,
            "published_date": entry.published.text,
            "description": entry.media.description.text,
            "view_count": entry.statistics.view_count,
            "duration": entry.media.duration.seconds,
            "author": author
        }
        return info

    def _get_youtube_info(self, backend):
        yt_service = gdata.youtube.service.YouTubeService()
        yt_service.ssl = True
        yt_service.developer_key = settings.GOOGLE_DEVELOPER_KEY
        yt_service.client_id = settings.GOOGLE_CLIENT_ID

        entry = yt_service.GetYouTubeVideoEntry(video_id=backend.code)
        info = self._generate_youtube_info(entry)

        return info

    def save(self, *args, **kwargs):
        super(VideoLesson, self).save(*args, **kwargs)

        if not self.info:
            backend = detect_backend(self.video)

            if backend.backend == "VimeoBackend":
                info = backend.info
            elif backend.backend == "YoutubeBackend":
                entry = kwargs.get('entry', None)
                if entry:
                    info = self._generate_youtube_info(entry)
                else:
                    info = self._get_youtube_info(backend)
                info.update({"id": backend.code})

            info.update({"backend": backend.backend})
            info.update({"thumbnail": backend.thumbnail})
            self.info = info
            if not self.title:
                self.title = info['title']
            slug = "%s-%s" % (self.id, slugify(self.title))
            slug = slug[:-1] if slug[-1] == "-" else slug
            self.slug = slug
            if not self.duration:
                self.duration = info['duration']
            self.backend_source = backend.backend
            self.thumbnail = backend.thumbnail

            # Assign Meta content
            if not self.meta_description:
                if info['description']:
                    self.meta_description = info['description']
                else:
                    self.meta_description = info['title']

            if not self.meta_title:
                self.meta_title = info['title']

            self.save()

    def get_absolute_url(self):
        return "%s%s" % (settings.SITE_FULL_DOMAIN, reverse('video_detail', args=(self.slug, )))


class HomePageVideo(models.Model):
    """
    Contains ad script of a particular :model:'lessons.HomePageVideo' instance.
    """
    category = TreeForeignKey(Category)
    video = models.ForeignKey(VideoLesson)

    class Meta:
        verbose_name = "Home Page Video"
        verbose_name_plural = "Home Page Videos"

templates/blog/blog_post_detail.html
{% extends "blog/blog_post_list.html" %}
{% load mezzanine_tags comment_tags keyword_tags rating_tags i18n future disqus_tags %}

{% block meta_title %}{{ blog_post.meta_title }}{% endblock %}

{% block meta_keywords %}{% metablock %}
{% keywords_for blog_post as tags %}
{% for tag in tags %}{% if not forloop.first %}, {% endif %}{{ tag }}{% endfor %}
{% endmetablock %}{% endblock %}

{% block meta_description %}{% metablock %}
{{ blog_post.description }}
{% endmetablock %}{% endblock %}

{% block title %}
{% editable blog_post.title %}{{ blog_post.title }}{% endeditable %}
{% endblock %}

{% block breadcrumb_menu %}
{{ block.super }}
<li class="active">{{ blog_post.title }}</li>
{% endblock %}

{% block main %}
    <div class="blogdetail sections">
        <div class="bootstrap-carousel">
            <div class="carousel slide" id="carousel-example-captions">
                {% block blog_post_detail_featured_image %}
                {% if settings.BLOG_USE_FEATURED_IMAGE and blog_post.featured_image %}
                    <div class="carousel-inner">
                        <div class="item active">
                            <img class="img-responsive" src="{{ MEDIA_URL }}{% thumbnail blog_post.featured_image 600 0 %}">
                        </div>
                    </div>
                {% endif %}
                {% endblock %}
            </div>
        </div>

        <div class="row">
            <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                <div class="avatar">
                    {% block blog_post_detail_postedby %}
                        {% editable blog_post.publish_date %}
                            {% with blog_post.user as author %}
                            <figure>
                                <a href="blog-fullwidth.html"><img src="{{ STATIC_URL }}theme/images/avatar.gif" alt=""></a>
                            </figure>
                            <h5>By <a href="{% url "blog_post_list_author" author %}">{{ author.get_full_name|default:author.username }}</a></h5>
                            <p>
                                {% blocktrans with sometime=blog_post.publish_date|timesince %}{{ sometime }} ago{% endblocktrans %}
                            </p>
                            {% endwith %}
                        {% endeditable %}
                    {% endblock %}
                </div>
            </div>
            <div class="col-lg-9 col-md-8 col-sm-8 col-xs-12">
                <div class="blogtext blog-description">
                    <h2 class="heading">{% editable blog_post.title %}{{ blog_post.title }}{% endeditable %}</h2>
                    <div class="clearfix"></div>
                    <div class="blogmetas">
                        <ul>
                            <li><i class="fa fa-calendar"></i>{{ blog_post.publish_date }}</li>
                            <li>
                                <i class="fa fa-align-justify"></i>
                                {% with blog_post.categories.all as categories %}
                                {% if categories %}
                                {% for category in categories %}
                                <a href="{% url "blog_post_list_category" category.slug %}">{{ category }}</a>{% if not forloop.last %}, {% endif %}
                                {% endfor %}
                                {% endif %}
                                {% endwith %}
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <p>
                        {% block blog_post_detail_content %}
                            {% editable blog_post.content %}
                                {{ blog_post.content|richtext_filters|safe }}
                            {% endeditable %}
                        {% endblock %}
                    </p>
                </div>
            </div>
        </div>
    </div>
    <!-- Blog Detail End -->
    <div class="clearfix"></div>
    <!-- Contents Section Started -->
    <div class="sections">
        <h2 class="heading">Related Posts</h2>
        <div class="clearfix"></div>
        <div class="row">
            {% block blog_post_detail_related_posts %}
                {% if blog_post.related_posts.all %}
                    {% for post in blog_post.related_posts.all %}
                        <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12">
                            <div class="blogposttwo">
                                <figure>
                                    {% if settings.BLOG_USE_FEATURED_IMAGE and blog_post.featured_image %}
                                    <a href="{{ post.get_absolute_url }}">
                                        <img src="{{ MEDIA_URL }}{% thumbnail post.featured_image 300 300 %}" class="img-responsive hovereffect" alt="" />
                                    </a>
                                    {% endif %}
                                </figure>
                                <div class="text">
                                    <h4><a href="blogdetail-double-sidebar.html"><a href="{{ post.get_absolute_url }}">{{ post.title|truncatechars:20 }}</a></h4>
                                    <ul>
                                        <li><i class="fa fa-calendar"></i>{{ post.publish_date }}</li>
                                        <li>
                                            <i class="fa fa-align-justify"></i>
                                            {% with post.categories.all as categories %}
                                            {% if categories %}
                                            {% for category in categories %}
                                            <a href="{% url "blog_post_list_category" category.slug %}">{{ category }}</a>{% if not forloop.last %}, {% endif %}
                                            {% endfor %}
                                            {% endif %}
                                            {% endwith %}
                                        </li>
                                    </ul>
                                    <a href="{{ post.get_absolute_url }}" class="btn btn-primary btn-xs backcolor">Read More</a>
                                </div>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                    {% endfor %}
                {% endif %}
            {% endblock %}
            
        </div>
    </div>
    <!-- Contents Section End -->
    <div class="clearfix"></div>
    <!-- Contents Section Started -->
    <div class="sections">
        {% block blog_post_detail_commentlink %}
        <h2 class="heading">
            {% if blog_post.allow_comments %}
                {% if settings.COMMENTS_DISQUS_SHORTNAME %}
                    <a href="{{ blog_post.get_absolute_url }}#disqus_thread"
                        data-disqus-identifier="{% disqus_id_for blog_post %}">{% spaceless %}
                        {% trans "Comments" %}
                    {% endspaceless %}</a>
                {% else %}(<a href="#comments">{% spaceless %}
                    {% blocktrans count comments_count=blog_post.comments_count %}{{ comments_count }} comment{% plural %}{{ comments_count }} comments{% endblocktrans %}
                    {% endspaceless %}</a>)
                {% endif %}
            {% endif %}
        </h2>
        {% endblock %}
        {% block blog_post_detail_comments %}
            {% if blog_post.allow_comments %}{% comments_for blog_post %}{% endif %}
        {% endblock %}
    </div>
    <!-- Contents Section End -->
    <div class="clearfix"></div>        

{% endblock %}

{% block sidebar_ads %}
    {% for ad in blog_post.blogadvertisement_set.all %}
        <!-- Advertisement start -->
        <div class="widget center">
            {{ ad.ad_script|safe }}
        </div>
        <div class="clearfix"></div>
        <!-- Advertisement End -->
    {% endfor %}
{% endblock %}

templates/blog/blog_post_list.html
{% extends "base.html" %}
{% load i18n future mezzanine_tags blog_tags keyword_tags disqus_tags %}

{% block meta_title %}{% if page %}{{ page.meta_title }}{% else %}{% trans "Blog" %}{% endif %}{% endblock %}

{% block meta_keywords %}{% metablock %}
{% keywords_for page as keywords %}
{% for keyword in keywords %}
    {% if not forloop.first %}, {% endif %}
    {{ keyword }}
{% endfor %}
{% endmetablock %}{% endblock %}

{% block meta_description %}{% metablock %}
{{ page.description }}
{% endmetablock %}{% endblock %}

{% block title %}
{% if page %}
{% editable page.title %}{{ page.title }}{% endeditable %}
{% else %}
{% trans "Blog" %}
{% endif %}
{% endblock %}

{% block breadcrumb_menu %}
    {{ block.super }}
    <li><a href="{% url 'blog_post_list' %}">Blog</a></li>
    {% if tag or category or year or month or author %}
    <li>{% spaceless %}
    {% if tag %}
        {% trans "Tag:" %} {{ tag }}
    {% else %}{% if category %}
        {% trans "Category:" %} {{ category }}
    {% else %}{% if year or month %}
        {% if month %}{{ month }}, {% endif %}{{ year }}
    {% else %}{% if author %}
        {% trans "Author:" %} {{ author.get_full_name|default:author.username }}
    {% endif %}{% endif %}{% endif %}{% endif %}
    {% endspaceless %}
    </li>
    {% endif %}
{% endblock %}

{% block main %}
<div class="sections">

<div class="row lessons-div">
    {% for blog_post in blog_posts.object_list %}
        <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12"> 

            <div class="blogposttwo">
                <figure>
                    {% if settings.BLOG_USE_FEATURED_IMAGE and blog_post.featured_image %}
                    {% block blog_post_list_post_featured_image %}
                    <a href="{{ blog_post.get_absolute_url }}">
                        <img alt="" class="img-responsive hovereffect" src="{{ MEDIA_URL }}{% thumbnail blog_post.featured_image 300 300 %}">
                    </a>
                    {% endblock %}
                    {% endif %}
                </figure>
                <div class="text blog-description">
                    {% block blog_post_list_post_title %}
                    {% editable blog_post.title %}
                    <h4><a href="{{ blog_post.get_absolute_url }}">{{ blog_post.title|truncatechars:20 }}</a></h4>
                    {% endeditable %}
                    {% endblock %}
                    {% block blog_post_list_post_metainfo %}
                    {% editable blog_post.publish_date %}
                    <ul>
                        <li><i class="fa fa-calendar"></i>{{ blog_post.publish_date }}</li>
                        <li>
                            <i class="fa fa-align-justify"></i>
                            {% with blog_post.categories.all as categories %}
                            {% if categories %}
                            {% for category in categories %}
                            <a href="{% url "blog_post_list_category" category.slug %}">{{ category }}</a>{% if not forloop.last %}, {% endif %}
                            {% endfor %}
                            {% endif %}
                            {% endwith %}                            
                        </li>
                    </ul>
                    {% endeditable %}
                    {% endblock %}
                    {% block blog_post_list_post_content %}
                    {% editable blog_post.content %}
                    <p>
                        {{ blog_post.description_from_content|safe|truncatechars:50 }}
                    </p>                    
                    {% endeditable %}
                    {% endblock %}
                    <a class="btn btn-primary btn-xs backcolor" href="{{ blog_post.get_absolute_url }}">{% trans "read more" %}</a>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
    {% endfor %}
</div>

{% pagination_for blog_posts %}

{% if settings.COMMENTS_DISQUS_SHORTNAME %}
{% include "generic/includes/disqus_counts.html" %}
{% endif %}

</div>
{% endblock %}

{% block right_panel %}
{% include "blog/includes/filter_panel.html" %}
{% endblock %}

{% block sidebar_ads %}
    {% for blog_post in blog_posts.object_list %}
        {% for ad in blog_post.blogadvertisement_set.all %}
            {% if mycycle < 5 %} 
                <!-- {% cycle 1 2 3 4 5 6 as mycycle %} -->
                <!-- Advertisement start -->
                <div class="widget center">
                    {{ ad.ad_script|safe }}
                </div>
                <div class="clearfix"></div>
                <!-- Advertisement End -->
            {% endif %}
        {% endfor %}
    {% endfor %}
{% endblock %}